# Generated by Django 2.1.15 on 2021-11-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tempclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempClass',
        ),
    ]
