# Generated by Django 2.1.15 on 2021-11-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id_app', models.AutoField(db_column='ID_app', primary_key=True, serialize=False)),
                ('application_name', models.CharField(blank=True, db_column='Application_name', max_length=100)),
                ('developer', models.CharField(blank=True, db_column='Developer', max_length=100, null=True)),
            ],
            options={
                'db_table': 'App',
            },
        ),
        migrations.CreateModel(
            name='ProgLanguage',
            fields=[
                ('id_language', models.AutoField(db_column='ID_language', primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, db_column='Language_name', max_length=100)),
                ('descript', models.CharField(blank=True, db_column='Descript', max_length=1000, null=True)),
                ('creation_year', models.IntegerField(blank=True, db_column='Creation_year', null=True)),
            ],
            options={
                'db_table': 'Prog_language',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='id_language',
            field=models.ForeignKey(blank=True, db_column='ID_language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.ProgLanguage'),
        ),
    ]
